### ISSUE TITLE
ResourceLib 2.0 beta is no longer signed with a strong name key file

### ISSUE THREAD

**Issue by icnocop** [resourcelib/resourcelib#62]
Hi.

I updated from ResourceLib 1.6.422.0 to 2.0.0-ci0018 and noticed ResourceLib.dll is no longer a strongly-named assembly.

I reference ResourceLib in a project targeting .net 4.0 which is strongly named and so it requires all referenced assemblies to also be strongly-named.

Otherwise, I get the following exception:

> System.IO.FileLoadException: Could not load file or assembly 'ResourceLib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

I noticed commit https://github.com/resourcelib/resourcelib/commit/949fa6cbe9a4d882a04fb08b85a622e7ef17a3e2 removed references to Key.snk and commit https://github.com/resourcelib/resourcelib/commit/bd81c1c5032ac9c8145ec23b5b882b151662dc24 removed the Key.snk file.

Is there a reason against ResourceLib.dll being strongly named?

Thank you.

**Comment by thoemmi** [comment]
Hey, it's 2018... still relying on strong-naming?

Microsoft [writes about strong-naming](https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md#faq):

> ### 1. Microsoft strong-names their assemblies, should I?
> For the most part, the majority of applications and libraries do not need strong-names. Strong-names are left over from previous eras of .NET where [sandboxing](http://en.wikipedia.org/wiki/Sandbox_(computer_security)) needed to differentiate between code that was trusted, versus code that was untrusted. However in recent years, sandboxing via AppDomains, especially to [isolate ASP.NET web applications] (http://support.microsoft.com/kb/2698981), is no longer guaranteed and is not recommended.

There is an [interesting thread about the pros and cons of SN](https://github.com/Microsoft/XamlBehaviors/pull/29?w=1#issuecomment-162572491) in the **Microsoft/XamlBehaviors** repository, I don't want to repeat the arguments here.

IMHO we should get rid of strong-naming, that's why I have dropped it in resourcelib. If you're really depending on strong-naming, you can compile the source by yourself ore use the [Strong Namer](https://github.com/dsplaisted/strongnamer) from Daniel Plaisted (@dsplaisted) or [Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner) from Werner van Deventer (@brutaldev).

**Comment by icnocop** [comment]
Thank you for the detailed response, Thomas!

Should we add something to the change log?

**Comment by thoemmi** [comment]
Yes, thanks for the hint. I'm going to update the change log.
